inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

##### OVERRIDES OF STANDARD CONFIGS #####
AllCops:
  NewCops: enable
  Exclude:
  - 'db/schema.rb'
  - 'bin/**'
  - 'config/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false