inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails

##### OVERRIDES OF STANDARD CONFIGS #####
AllCops:
  NewCops: enable
  Exclude:
  - 'db/schema.rb'
  - 'bin/**'
  - 'config/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false